---
- name: Server preparation and application deployment
  hosts: immich_servers
  become: yes

  tasks:

    # --- DOCKER INSTALLATION ---

    # Install helper tools for secure SSL verification (ca-certs), data fetching (curl), and signature validation (gnupg)
    - name: Install required system packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    # Download GPG key
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Register Docker's official server as a trusted source for the 'focal' (20.04) system version
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    # Install the Docker engine, command-line interface, container runtime, and Compose V2 plugin
    - name: Install Docker and Compose V2 plugin
      apt:
        name:
          - docker-ce           # installing the package will automatically start and enable docker (autostart after reboot)
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - cifs-utils
        state: present
        update_cache: yes

# --- FILE DEPLOYMENT ---

    - name: Create target directory on the server
      file:
        path: /opt/app
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml
      copy:
        src: "{{ playbook_dir }}/../app/docker-compose.yml"
        dest: /opt/app/docker-compose.yml

    # --- DYNAMIC SECRET FETCHING  ---

    - name: Get Access Token from Azure Metadata Service
      uri:
        # this specific URL is used by major cloud providers—including Google Cloud Platform (GCP), AWS, and Azure—to host an Instance Metadata Service
        url: "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://vault.azure.net"
        headers:
          Metadata: "true"
      register: token_response    # save the tocken in var token_response

    - name: Fetch database password from Key Vault via REST API
      uri:
        url: "https://{{ keyvault_name }}.vault.azure.net/secrets/immich-db-pass?api-version=7.4"
        method: GET
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
      register: vault_db_password
      no_log: true                # for security purposes do not put pwd explicitly in the logs

    - name: Fetch file share password from Key Vault via REST API
      uri:
        url: "https://{{ keyvault_name }}.vault.azure.net/secrets/{{ immich_storage_key_name }}?api-version=7.4"
        method: GET
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
      register: vault_storage_key
      no_log: true                # for security purposes do not put pwd explicitly in the logs

    - name: Create .env file on the remote server
      copy:
        dest: /opt/app/.env
        content: |
          UPLOAD_LOCATION=./library
          DB_DATA_LOCATION=./postgres
          IMMICH_VERSION=release
          DB_PASSWORD={{ vault_db_password.json.value }}
          DB_USERNAME=postgres
          DB_DATABASE_NAME=immich
          STORAGE_KEY={{ vault_storage_key.json.value }}
          STORAGE_SHARE={{ file_share_name }}
          STORAGE_ACCOUNT={{ storage_account_name }}
        mode: '0600'

    # --- EXECUTION ---

    # Even though the service is automatically started in the task Install Docker and Compose V2 plugin we will start it expicitely
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    # Compse the immich docker-compse file
    - name: Start Immich via Docker Compose
      command: docker compose up -d
      args:
        chdir: /opt/app

    # install azure cli in order to get acces to ACR
    - name: Install Azure cli
      shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash
      args:
        creates: /usr/bin/az

    # pull and start nginx using ACR
    - name: Login to ACR via Managed Identity
      shell: |
        az login --identity
        az acr login --name {{ acr_name }}

    - name: Pull and Start Nginx Proxy
      shell: |
        docker pull {{ acr_name }}.azurecr.io/immich-proxy:latest
        docker rm -f immich-proxy || true
        docker container run -d \
          --name immich-proxy \
          -p 80:80 \
          --network immich_default \
          {{ acr_name }}.azurecr.io/immich-proxy:latest