server {

    # listen on port 80
    listen 80;
    server_name localhost;

    location / {
        # forward all requests to the Immich server container on port 2283 (default port for immich)
        proxy_pass http://immich-server:2283;

        # pass the original host header to the backend
        proxy_set_header Host $host;

        # pass the real client IP to the backend for logging and security
        proxy_set_header X-Real-IP $remote_addr;

        # standard header to track the chain of proxies the request passed through
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}